---
name: Env-Export
version: 0.10
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: Automatically export environment variables as constant-subs
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Env-Export
  homepage: http://search.cpan.org/dist/Env-Export
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/env-export/tree/master
requires:
  File::Spec: 0.8
  perl: 5.006
build_requires:
  Module::Build: 0.28
  Test::More: 0.80
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  Env::Export:
    file: lib/Env/Export.pm
    version: 0.10
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
